#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := solar_meter

# add extra directories to the component search path`
EXTRA_COMPONENT_DIRS+= components/application
EXTRA_COMPONENT_DIRS+= components/common
EXTRA_COMPONENT_DIRS+= components/device_drivers
EXTRA_COMPONENT_DIRS+= components/peripheral_drivers


# COMPONENT_INCLUDES+= Source/Peripherals/includes

include $(IDF_PATH)/make/project.mk

